name: Build N-Zik Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stable
        uses: actions/checkout@v4
        with:
          ref: v2.7.0
          submodules: true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleFull

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: N-Zik-APK
          path: composeApp/build/outputs/apk/**/*.apk
